- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup2
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup2
      name: myVnet2
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup2
      name: mySubnet2
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet2
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup2
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup2
      name: myNetworkSecurityGroup2
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup2
      name: myNIC2
      virtual_network: myVnet2
      subnet: mySubnet2
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup2
  - name: Create VM
    azure_rm_virtualmachine:
      name: MyVM
      resource_group: myResourceGroup2
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDwI0/vYLgM+gtpQN9rIDiAXP2NsRotsIJHU5qWAzWYt3ImaOEZTH4shOQmLouZdV08ATZCm4qKa7caGAu15FFSegL2pJc9ETrh8kCitPRCi/AXHin3fDLD6DBpAMpGhiTO2/hzu1kMhGvEFAfDL6hXo5LfFoY1aLAHpY7Q9cLYr1BlTgEkFdEOM5opH5/0fdkm7jxQl69ckHNznCkGcq8Vr35k1R2yWHvw0KGgSt+RNoPyuOHev16GV+dEWgmDQMm3NSrBGWtBmbSx6t+d32fUhnGzAjTur+e9d1L8ZYYkI8tk2KYcIJ8c0tTNkdXokEDX0L6U6eBSaoGfcFMSP6CkNi9k7RSVzK+AuAkVGwMl1cCAbsdpcAjSXqWMGg+L6+K/ik/sTJ2ky5vG1ikzv93oYcHtUfE17ORS3FQVQi1n+GzDUpEYyasyzDdi3EjqYeumcxBV17j1ipBZ5UVmJ+udcO/9cCQa8ilaiU20GjT/OrsYY0JaUGe+P8QwneImZ5FaV674lRI65lkq2l3Nxu0hbNySZHOuU6cJz8yz578gaWRFtIwDFV6jYWfjU4KfMtG4atckKAhry7MRLhf/8fauPdqYzZCpPUEkTxALmHltYjGK9Vdb5iRZ/7JpRImysUnH9ZtTnPrIsKYNPxtE/MYvfQRRRDruU9QIawyhmv5mDQ==
      network_interfaces: myNIC2
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
