---
- hosts: "{{ variable_host | default('web') }}"
  become: false
  tasks:
  - name: Install Nginx Latest
    yum:
      name: nginx
      state: latest
  - name: Start Nginx
    service:
      name: nginx
      state: started
