---
- hosts: "{{ variable_host | default('localhost') }}"
  become: false
  tasks:
- name: Install MariaDB 
  vars:
    mariadb_bind_address: '0.0.0.0'
    mariadb_root_password: '&othErEek97FrewlAyd?'
    mariadb_databases:
      - name: wordpress_db
    mariadb_users:
      - name: wordpress_usr
        password: ywIapecJalg6
        priv: wordpress_db.*:ALL
        host: '10.1.1.%'
