 -name: Install NGINX
  hosts: "{{ variable_host | default('localhost') }}"
  become: yes
  tasks:
  - name: Install Nginx Latest
    yum:
      name: nginx
      state: latest
  - name: Start Nginx
    service:
      name: nginx
      state: started
